const books = [
  {
    id: 1,
    title: "Flowers for Algernon",
    author: "Daniel Keyes",
    cover: "../assets/images/Flowers for Algernon.jpg",
    description: "A heartwarming science fiction novel about a man’s struggle with intelligence and identity.",
    date: "March 1966",
    length: "311 pages",
    language: "English",
    category: "Drama",
    tag: "Bestseller",
    rating: "⭐ 9.5",
    isbn: "978-0-06-285326-7",  
    price: "$14.99"  
  },
  {
    id: 2,
    title: "A Clockwork Orange",
    author: "Anthony Burgess",
    cover: "../assets/images/A Clockwork Orange.jpg",
    description: "A dystopian satire that explores free will, the mind, and societal control.",
    date: "1962",
    length: "192 pages",
    language: "English",
    category: "Drama",
    tag: "Bestseller",
    rating: "⭐ 9.0",
    isbn: "978-0-14-118260-4",  
    price: "$12.99"  
  },
  {
    id: 3,
    title: "Pet Sematary",
    author: "Stephen King",
    cover: "../assets/images/Pet Sematary.jpg",
    description: "A chilling horror novel about resurrection and the consequences of bringing loved ones back from the dead.",
    date: "November 1983",
    length: "374 pages",
    language: "English",
    category: "Horror",
    tag: "Bestseller",
    rating: "⭐ 9.2",
    isbn: "978-0-671-48613-9",  
    price: "$16.99"  
  },
  {
    id: 4,
    title: "1984",
    author: "George Orwell",
    cover: "../assets/images/1984.jpg",
    description: "A dystopian novel about surveillance, totalitarianism, and the loss of individuality.",
    date: "1949",
    length: "328 pages",
    language: "English",
    category: "Drama",
    tag: "Classic",
    rating: "⭐ 9.8",
    isbn: "978-0-452-28423-4",  
    price: "$13.99"  
  },
  {
    id: 5,
    title: "Brave New World",
    author: "Aldous Huxley",
    cover: "../assets/images/Brave New World.jpg",
    description: "A futuristic world where technology and social engineering shape society.",
    date: "1932",
    length: "311 pages",
    language: "English",
    category: "Drama",
    tag: "Bestseller",
    rating: "⭐ 9.4",
    isbn: "978-0-06-085052-3",  
    price: "$15.49"  ,
  },
    {
      "id": 7,
      "title": "Animal Farm",
      "author": "George Orwell",
      "cover": "../assets/images/Animal Farm.jpg",
      "description": "An allegorical novella that satirizes political events and corruption through a farmyard revolution.",
      "date": "1945",
      "length": "112 pages",
      "language": "English",
      "category": "Political Satire",
      "tag": "Classic",
      "rating": "⭐ 8.7",
      "isbn": "978-0-452-28424-1",
      "price": "$6.99"
    },
    {
      "id": 8,
      "title": "A Tale of Two Cities",
      "author": "Charles Dickens",
      "cover": "../assets/images/A Tale of Two Cities.jpg",
      "description": "A historical novel set during the French Revolution, exploring themes of resurrection and social justice.",
      "date": "1859",
      "length": "489 pages",
      "language": "English",
      "category": "Historical Fiction",
      "tag": "Classic",
      "rating": "⭐ 9.0",
      "isbn": "978-0-14-143960-3",
      "price": "$7.99"
    },
    {
      "id": 9,
      "title": "Great Expectations",
      "author": "Charles Dickens",
      "cover": "../assets/images/Great Expections.jpg",
      "description": "A coming-of-age novel about an orphan named Pip, his adventures, and the moral lessons he learns.",
      "date": "1861",
      "length": "544 pages",
      "language": "English",
      "category": "Bildungsroman",
      "tag": "Classic",
      "rating": "⭐ 8.8",
      "isbn": "978-0-14-143956-6",
      "price": "$9.99"
    },
    {
      "id": 10,
      "title": "Oliver Twist",
      "author": "Charles Dickens",
      "cover": "../assets/images/Oliver Twist.jpg",
      "description": "The story of an orphan boy who runs away from a workhouse and faces many challenges in Victorian London.",
      "date": "1837",
      "length": "436 pages",
      "language": "English",
      "category": "Social Novel",
      "tag": "Classic",
      "rating": "⭐ 9.0",
      "isbn": "978-0-14-143974-0",
      "price": "$8.99"
    },
    {
      "id": 11,
      "title": "Mrs. Dalloway",
      "author": "Virginia Woolf",
      "cover": "../assets/images/Mrs. Dalloway.jpg",
      "description": "A novel that captures a day in the life of Clarissa Dalloway, exploring themes of time, memory, and mental health.",
      "date": "1925",
      "length": "216 pages",
      "language": "English",
      "category": "Modernist",
      "tag": "Literary Fiction",
      "rating": "⭐ 9.1",
      "isbn": "978-0-15-662870-9",
      "price": "$10.99"
    },
    {
      "id": 12,
      "title": "To the Lighthouse",
      "author": "Virginia Woolf",
      "cover": "../assets/images/To The Lighthouse.jpg",
      "description": "A modernist novel focusing on the Ramsay family’s visit to the Isle of Skye, examining themes of time, change, and family dynamics.",
      "date": "1927",
      "length": "209 pages",
      "language": "English",
      "category": "Modernist",
      "tag": "Literary Fiction",
      "rating": "⭐ 9.3",
      "isbn": "978-0-15-690739-2",
      "price": "$12.99"
    },
    {
      "id": 13,
      "title": "Orlando",
      "author": "Virginia Woolf",
      "cover": "../assets/images/Orlando.jpg",
      "description": "A fantastical story that follows Orlando, a young nobleman who changes gender and lives for centuries, exploring themes of identity and time.",
      "date": "1928",
      "length": "368 pages",
      "language": "English",
      "category": "Biographical Fiction",
      "tag": "Modernist",
      "rating": "⭐ 8.5",
      "isbn": "978-0-15-670140-0",
      "price": "$11.99"
    },
    {
      "id": 14,
      "title": "War and Peace",
      "author": "Leo Tolstoy",
      "cover": "../assets/images/War And Peace.jpg",
      "description": "A historical epic that follows the lives of Russian aristocrats during the Napoleonic Wars.",
      "date": "1869",
      "length": "1,225 pages",
      "language": "Russian",
      "category": "Historical Fiction",
      "tag": "Classic",
      "rating": "⭐ 9.8",
      "isbn": "978-0-14-303999-0",
      "price": "$19.99"
    },
    {
      "id": 15,
      "title": "Anna Karenina",
      "author": "Leo Tolstoy",
      "cover": "../assets/images/Anna Karenina.jpg",
      "description": "A tragic love story set in 19th century Russia, exploring the consequences of infidelity and societal expectations.",
      "date": "1878",
      "length": "864 pages",
      "language": "Russian",
      "category": "Literary Fiction",
      "tag": "Classic",
      "rating": "⭐ 9.7",
      "isbn": "978-0-14-303500-9",
      "price": "$15.99"
    },
    {
      "id": 16,
      "title": "The Death of Ivan Ilyich",
      "author": "Leo Tolstoy",
      "cover": "../assets/images/The Death Of Ivan Ilyich.jpg",
      "description": "A novella about the life and death of Ivan Ilyich Golovin, exploring the meaning of life and confronting the inevitability of death.",
      "date": "1886",
      "length": "144 pages",
      "language": "Russian",
      "category": "Philosophical Fiction",
      "tag": "Classic",
      "rating": "⭐ 9.3",
      "isbn": "978-0-14-044255-7",
      "price": "$7.99"
    },
    {
      "id": 17,
      "title": "Thus Spoke Zarathustra",
      "author": "Friedrich Nietzsche",
      "cover": "../assets/images/Thus Spoke Zarathustra.jpg",
      "description": "A philosophical novel that presents the teachings of Zarathustra, a prophet who preaches the concept of the Übermensch and the will to power.",
      "date": "1883",
      "length": "350 pages",
      "language": "German",
      "category": "Philosophy",
      "tag": "Classic",
      "rating": "⭐ 9.1",
      "isbn": "978-0-14-044118-5",
      "price": "$12.99"
    },
    {
      "id": 18,
      "title": "Beyond Good and Evil",
      "author": "Friedrich Nietzsche",
      "cover": "../assets/images/Beyond Good And Evil.jpg",
      "description": "A philosophical work in which Nietzsche explores the nature of morality, free will, and the relationship between truth and power.",
      "date": "1886",
      "length": "288 pages",
      "language": "German",
      "category": "Philosophy",
      "tag": "Classic",
      "rating": "⭐ 9.0",
      "isbn": "978-0-14-044133-8",
      "price": "$10.99"
    },
    {
      "id": 19,
      "title": "The Birth of Tragedy",
      "author": "Friedrich Nietzsche",
      "cover": "../assets/images/The Birth Of Tragedy.jpg",
      "description": "Nietzsche's first major work, in which he discusses the origins of Greek tragedy and its relation to the concept of the Dionysian and Apollonian.",
      "date": "1872",
      "length": "220 pages",
      "language": "German",
      "category": "Philosophy",
      "tag": "Classic",
      "rating": "⭐ 8.8",
      "isbn": "978-0-14-044229-8",
      "price": "$9.99"
    },
      {
        "id": 20,
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "cover": "../assets/images/The Great Gatsby.jpg",
        "description": "A tragic story about Jay Gatsby and his obsession with the elusive Daisy Buchanan, set during the Jazz Age of the 1920s.",
        "date": "1925",
        "length": "180 pages",
        "language": "English",
        "category": "Novel",
        "tag": "Classic",
        "rating": "⭐ 9.6",
        "isbn": "978-0-7432-7356-5",
        "price": "$9.99"
      },
      {
        "id": 21,
        "title": "Brave New World",
        "author": "Aldous Huxley",
        "cover": "../assets/images/Brave New World.jpg",
        "description": "A dystopian novel about a future society driven by consumerism and the control of emotions, where individuality is suppressed.",
        "date": "1932",
        "length": "311 pages",
        "language": "English",
        "category": "Dystopian",
        "tag": "Classic",
        "rating": "⭐ 9.3",
        "isbn": "978-0-06-085052-4",
        "price": "$8.99"
      },
    ]
    